TRAIN:
  MODEL_NAME: infgrad/stella-base-en-v2  # sentence-transformers/all-mpnet-base-v2  #gte-base-en-v1.5
  N_EPOCHS: 3
  BATCH_SIZE: 8
  INIT_LEARNING_RATE: 0.00005  # 5e-5
  USE_DETERMINISTIC_ALGORITHMS: False
  SEED: 100
  TRAIN_VAL_SPLIT: [0.8, 0.1]
  LOSS:  # TripletMarginLoss
      p: 2
      margin: 0.1
      eps: 0.000001
  SAVE_MODEL_PERIOD: 1
